// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShopSys.Data.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int? CusId { get; set; }

    public DateOnly OrderDate { get; set; }

    public double TotalPrice { get; set; }

    public virtual Customer Cus { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}